import type { CapacitorConfig } from '@capacitor/cli';

/**
 * Teampurex — Capacitor configuration.
 *
 * Strategy: HOSTED MODE.
 *   The Android app is a thin WebView pointing at https://www.teampurex.com.
 *   Every Next.js feature (server actions, Supabase auth via cookies,
 *   route-handler endpoints, ISR pages) works without any "API layer"
 *   refactor — the app simply IS the website, launched from the home
 *   screen as a real native app.
 *
 * Pros of hosted mode:
 *   • Zero static-export friction. Next.js stays fully dynamic.
 *   • Auth, server actions, all current features carry over instantly.
 *   • One source of truth — fix it on web, app gets the fix
 *     (no OTA tooling, no rebundle).
 *
 * Trade-offs:
 *   • Requires internet on first load. We add an offline page later.
 *   • Slight first-paint delay vs bundled assets (~300ms on 4G).
 *
 * Future: when we want OFFLINE-FIRST behaviour (logging workouts at
 * the gym with patchy signal), we switch this to bundled mode +
 * static-export the routes that need to work offline. Out of scope
 * for v1.
 */
const config: CapacitorConfig = {
  appId: 'com.teampurex.app',
  appName: 'Teampurex',
  // `webDir` is required by Capacitor's CLI even in hosted mode.
  // Points at Next's static-export directory — unused at runtime
  // because `server.url` overrides it, but the CLI validates it
  // exists. We create an empty `out/` directory in the repo so
  // `npx cap sync` doesn't error on a fresh clone.
  webDir: 'out',
  server: {
    // Cold-start optimisation: land on /client/dashboard directly.
    // For an already-authenticated user (99% of returning opens) the
    // page renders immediately — the previous "start on /login,
    // middleware redirects to /client/dashboard" flow was costing an
    // extra full round-trip on every cold-start.
    //
    // First-time / signed-out users still see the login screen — the
    // client-side middleware redirects them from /client/dashboard
    // to /login. That first-time hop is unavoidable and only happens
    // once per install.
    url: 'https://www.teampurex.com/client/dashboard',
    androidScheme: 'https',
    cleartext: false,
  },
  android: {
    // Hide the OS-level navigation bar when the keyboard opens so
    // form fields aren't pushed off-screen on small phones.
    adjustMarginsForEdgeToEdge: 'force',
    // Allow mixed content from teampurex.com (only used in dev when
    // we point to localhost). Production stays https-only.
    allowMixedContent: false,
    // Capacitor 7 default — webContentsDebuggingEnabled is true in
    // debug builds, false in release builds. Leave alone.
  },
  ios: {
    // Bundle ID matches Android. Apple namespace rules don't require
    // it to match but keeping them aligned simplifies asset reuse
    // and admin in App Store Connect / Play Console.
    //
    // Contents of this block are read by `npx cap sync ios`. The
    // actual ios/ folder is generated by `npx cap add ios`, which
    // MUST run on macOS — see docs/capacitor-ios-setup.md for the
    // Codemagic cloud-build path that handles this from Windows.
    contentInset: 'always',
    // Keep the status bar in the dark style (white icons on black)
    // matching the app's #0a0c09 background.
    preferredContentMode: 'mobile',
    // Allow the WebView to access the camera + microphone when the
    // user taps an input that needs them (profile photo upload).
    limitsNavigationsToAppBoundDomains: false,
    // Hide the toolbar overlay that iOS adds to remote URLs (gives
    // a more "native app" feel — without this the user sees a "Done"
    // button at the top of the WebView).
    backgroundColor: '#0a0c09',
  },
  plugins: {
    SplashScreen: {
      // Manual splash dismiss: launchAutoHide=false means the splash
      // stays up until we EXPLICITLY call SplashScreen.hide() from the
      // web app. The <NativeSplashDismisser> component in the root
      // layout fires that call the moment the first React tree
      // hydrates — so on a fast device the splash disappears in ~800
      // ms instead of the previous fixed 3500 ms wait.
      //
      // launchShowDuration=8000 is a safety-net fallback: if the JS
      // never hydrates for some reason (network stall, JS error),
      // the splash still dismisses on its own so the user isn't stuck.
      launchAutoHide: false,
      launchShowDuration: 8000,
      launchFadeOutDuration: 250,
      backgroundColor: '#0a0c09',
      androidScaleType: 'CENTER_CROP',
      showSpinner: false,
      androidSpinnerStyle: 'large',
      spinnerColor: '#c6ff3d',
      splashFullScreen: true,
      splashImmersive: true,
    },
    StatusBar: {
      // App is dark-themed; ask Android to render the status bar
      // icons in light style (white).
      style: 'dark',
      backgroundColor: '#0a0c09',
      overlaysWebView: false,
    },
  },
};

export default config;
