import type { CapacitorConfig } from '@capacitor/cli';

/**
 * Teampurex — Capacitor configuration.
 *
 * Strategy: HOSTED MODE.
 *   The Android app is a thin WebView pointing at https://www.teampurex.com.
 *   Every Next.js feature (server actions, Supabase auth via cookies,
 *   route-handler endpoints, ISR pages) works without any "API layer"
 *   refactor — the app simply IS the website, launched from the home
 *   screen as a real native app.
 *
 * Pros of hosted mode:
 *   • Zero static-export friction. Next.js stays fully dynamic.
 *   • Auth, server actions, all current features carry over instantly.
 *   • One source of truth — fix it on web, app gets the fix
 *     (no OTA tooling, no rebundle).
 *
 * Trade-offs:
 *   • Requires internet on first load. We add an offline page later.
 *   • Slight first-paint delay vs bundled assets (~300ms on 4G).
 *
 * Future: when we want OFFLINE-FIRST behaviour (logging workouts at
 * the gym with patchy signal), we switch this to bundled mode +
 * static-export the routes that need to work offline. Out of scope
 * for v1.
 */
const config: CapacitorConfig = {
  appId: 'com.teampurex.app',
  appName: 'Teampurex',
  // `webDir` is required by Capacitor's CLI even in hosted mode.
  // Points at Next's static-export directory — unused at runtime
  // because `server.url` overrides it, but the CLI validates it
  // exists. We create an empty `out/` directory in the repo so
  // `npx cap sync` doesn't error on a fresh clone.
  webDir: 'out',
  server: {
    // Land on the sign-in screen. Reverted from /client/dashboard on
    // 2026-07-16 after users on fresh installs got stuck on the splash
    // — /client/dashboard forces a middleware redirect to /login for
    // unauthenticated users which delayed the first paint enough that
    // the manual-dismiss splash timing got fragile. /login has no
    // auth check so it renders unconditionally fast.
    //
    // Signed-in users still cost one extra hop when middleware
    // redirects /login → /client/dashboard, but the login page is
    // static HTML and the hop is ~150 ms — negligible against the
    // reliability win on first install.
    url: 'https://www.teampurex.com/login',
    androidScheme: 'https',
    cleartext: false,
  },
  android: {
    // Hide the OS-level navigation bar when the keyboard opens so
    // form fields aren't pushed off-screen on small phones.
    adjustMarginsForEdgeToEdge: 'force',
    // Allow mixed content from teampurex.com (only used in dev when
    // we point to localhost). Production stays https-only.
    allowMixedContent: false,
    // Capacitor 7 default — webContentsDebuggingEnabled is true in
    // debug builds, false in release builds. Leave alone.
  },
  ios: {
    // Bundle ID matches Android. Apple namespace rules don't require
    // it to match but keeping them aligned simplifies asset reuse
    // and admin in App Store Connect / Play Console.
    //
    // Contents of this block are read by `npx cap sync ios`. The
    // actual ios/ folder is generated by `npx cap add ios`, which
    // MUST run on macOS — see docs/capacitor-ios-setup.md for the
    // Codemagic cloud-build path that handles this from Windows.
    contentInset: 'always',
    // Keep the status bar in the dark style (white icons on black)
    // matching the app's #0a0c09 background.
    preferredContentMode: 'mobile',
    // Allow the WebView to access the camera + microphone when the
    // user taps an input that needs them (profile photo upload).
    limitsNavigationsToAppBoundDomains: false,
    // Hide the toolbar overlay that iOS adds to remote URLs (gives
    // a more "native app" feel — without this the user sees a "Done"
    // button at the top of the WebView).
    backgroundColor: '#0a0c09',
  },
  plugins: {
    SplashScreen: {
      // Reverted 2026-07-16 from "launchAutoHide: false + manual
      // SplashScreen.hide()" back to auto-hide. The manual-hide
      // path relied on the JS hydrating successfully; when anything
      // in the load path stalled (slow 4G, an image request that
      // never finished, a hydration error), the splash sat forever
      // and the user reported "not even loading from logo".
      //
      // Auto-hide with a 2500 ms budget is the reliability floor:
      // the splash comes off after 2.5 s no matter what, even if
      // JS never runs.  <NativeSplashDismisser /> still fires
      // SplashScreen.hide() the moment React hydrates — on a fast
      // connection that dismisses at ~800 ms and the launchShow
      // Duration becomes an irrelevant ceiling. On a slow one the
      // 2.5 s guaranteed dismiss keeps the user from getting stuck.
      launchAutoHide: true,
      launchShowDuration: 2500,
      launchFadeOutDuration: 250,
      backgroundColor: '#0a0c09',
      androidScaleType: 'CENTER_CROP',
      showSpinner: false,
      androidSpinnerStyle: 'large',
      spinnerColor: '#c6ff3d',
      splashFullScreen: true,
      splashImmersive: true,
    },
    StatusBar: {
      // App is dark-themed; ask Android to render the status bar
      // icons in light style (white).
      style: 'dark',
      backgroundColor: '#0a0c09',
      overlaysWebView: false,
    },
  },
};

export default config;
