export const BRAND = {
  name: 'PURE X',
  tagline: 'Train for Life. Not Just Aesthetics.',
  whatsapp: '+919999999999', // replace with real number
  email: 'hello@purex.fit',
  locations: ['Hyderabad', 'London'],
} as const;

export const whatsappLink = (message = 'Hi PURE X, I would like to know more.') =>
  `https://wa.me/${BRAND.whatsapp.replace(/\D/g, '')}?text=${encodeURIComponent(message)}`;

// Fallback data — used before Supabase is wired. Admin panel will replace with DB reads.
export const FALLBACK_EXPERTS = [
  {
    slug: 'siva-reddy',
    name: 'Siva Reddy',
    title: 'Co-Founder & Personal Training Head',
    shortRole: 'PT Head',
    bioShort:
      'ICN medalist and architect of every PURE X training programme. Engineer-turned-coach with 300+ clients coached across strength, HYROX, rehab, and athletic performance.',
    credentials: [
      'ICN Gold 2024 — Best Transformation',
      'ICN Bronze 2024 — Men\'s Fitness Model',
      'Powerlifting Trainer (INPTA)',
      'Injury Rehabilitation Trainer',
      'Diploma in Personal Training',
      'Diploma in Nutrition',
    ],
    specialisms: [
      'HYROX Training',
      'Strength & Powerlifting',
      'Fat Loss',
      'Injury Rehab',
      'Calisthenics',
      'Post-Pregnancy Recovery',
    ],
    yearsExperience: 8,
    clientsTrained: 300,
    location: 'Hyderabad',
    photoUrl: '/experts/siva-reddy.jpg',
    stat: { num: '300+', label: 'Clients Coached' },
    bioLong: [
      'Siva Reddy is the architectural force behind every PURE X training programme. As Personal Training Head, he is responsible for the design, execution, and continuous refinement of all training systems — ensuring every client receives a structured, performance-driven, and scientifically grounded experience.',
      "Siva's journey into fitness was not conventional — it was built through personal transformation. A graduate in Electronics and Communications Engineering, he began his career in the corporate world, where prolonged stress and demanding work conditions significantly impacted his physical and mental health. This phase became a turning point, pushing him to take control of his lifestyle and rebuild his health from the ground up.",
      'Through disciplined training, structured programming, and consistent lifestyle changes, Siva achieved a remarkable 40kg weight loss — transforming not only his physique but his mindset and overall well-being. His transformation progressed to the competitive stage, where he achieved Gold Medal in Best Transformation and Bronze in Men\'s Fitness Model at ICN 2024.',
      'Following his transformation, Siva made a defining decision to leave his corporate career and pursue fitness professionally. He holds multiple professional certifications with accreditations aligned to INPTA and ISO-certified standards. With experience training 100+ clients across fat loss, muscle building, hormonal balance, post-pregnancy recovery, injury rehabilitation, and calisthenics, his coaching combines technical precision with practical adaptability.',
      'He is not just a trainer, but a system builder — developing structured pathways that transform individuals into stronger, healthier, and more capable versions of themselves.',
    ],
    responsibilities: [
      'Design fully personalised training programmes based on medical, physiotherapy, and fitness assessments',
      'Lead 1-on-1 and couples training sessions with strong emphasis on technique, safety, and progression',
      'Periodise programmes across structured training cycles to optimise performance and recovery',
      'Integrate strength training, endurance conditioning, and functional fitness into a unified system',
      'Apply specialised training strategies for fat loss, muscle gain, and performance development',
      'Implement rehabilitation-informed training in collaboration with the physiotherapist',
      'Deliver HYROX-based functional training systems and competition preparation protocols',
      'Conduct regular performance assessments and ensure progressive overload is effectively managed',
      'Track client progress across strength, endurance, and movement quality metrics',
      'Maintain high coaching standards, accountability, and consistency across all client interactions',
    ],
  },
  {
    slug: 'chandralekha',
    name: 'Chandralekha',
    title: 'Consultant Doctor',
    shortRole: 'Doctor',
    bioShort:
      'Government General Hospital physician bringing real clinical rigour to every PURE X programme. Turns fitness into medically supervised health transformation.',
    credentials: [
      'Practicing Doctor — Government General Hospital',
      'Pre-programme Medical Screening',
      'Cardiovascular & Metabolic Health',
      'Risk Stratification',
    ],
    specialisms: [
      'Medical Screening',
      'Cardiovascular Health',
      'Metabolic Assessment',
      'Chronic Condition Management',
      'Sustainable Health Habits',
    ],
    yearsExperience: 10,
    location: 'Hyderabad',
    photoUrl: '/experts/chandralekha.jpg',
    stat: { num: '100%', label: 'Medical Clearance' },
    bioLong: [
      'Chandralekha is the medical cornerstone of the PURE X model. Her presence transforms PURE X from a fitness service into a medically supervised health transformation programme — a distinction that is profoundly important for clients with health complexities, lifestyle-related conditions, or long-term wellness goals.',
      'She is currently practising as a doctor at a Government General Hospital, bringing real-world clinical experience and a strong foundation in patient care, diagnosis, and health monitoring. Her work in a high-demand medical environment equips her with the ability to assess, manage, and guide individuals across a wide spectrum of health conditions.',
      'Beyond her professional role, Chandralekha is also a mother of two, balancing the responsibilities of a demanding medical career with family life. This personal experience gives her a deeper understanding of the challenges many clients face — including time constraints, stress, lifestyle imbalance, and the need for sustainable, realistic health solutions.',
      'Her approach aligns closely with the PURE X philosophy — focusing not just on fitness, but on safe, sustainable, and long-term health transformation.',
    ],
    responsibilities: [
      'Conduct comprehensive pre-programme medical health screenings for all clients',
      'Assess cardiovascular, metabolic, and musculoskeletal health markers',
      'Provide medical clearance and risk stratification before training begins',
      'Monitor client health indicators throughout programme duration',
      'Advise on training limitations, contraindications, and medical modifications',
      'Support nutrition planning from a medical and health perspective',
      'Guide safe supplementation and recovery practices',
      'Provide ongoing medical consultations as part of integrated client care',
      'Collaborate with trainers and physiotherapists to ensure safe programme execution',
      'Identify early signs of health risks, overtraining, or lifestyle-related issues',
    ],
  },
  {
    slug: 'krishna',
    name: 'Krishna',
    title: 'Physiotherapist',
    shortRole: 'Physio',
    bioShort:
      'Prevention-first physiotherapy embedded into training from day one. 1,000+ clients treated, backed by 5+ years of hands-on clinical experience.',
    credentials: [
      'Certified Physiotherapist',
      'Rehabilitation Specialist',
      'Movement Screening Expert',
      '5+ Years Clinical Experience',
    ],
    specialisms: [
      'Injury Prevention',
      'Movement Screening',
      'Rehabilitation',
      'Mobility & Soft Tissue',
      'Return-to-Training Protocols',
      'Corrective Exercise',
    ],
    yearsExperience: 5,
    clientsTrained: 1000,
    location: 'Hyderabad',
    photoUrl: '/experts/krishna.jpg' as string | null,
    stat: { num: '1000+', label: 'Clients Treated' },
    bioLong: [
      'Krishna plays a critical role in ensuring that every PURE X client moves efficiently, recovers effectively, and trains consistently without setbacks. As the Physiotherapist, he brings a proactive, prevention-first approach that is deeply integrated into the PURE X training system.',
      'With over 5 years of professional experience and having supported 1,000+ clients, Krishna brings extensive hands-on expertise in injury prevention, rehabilitation, and movement optimisation. His work focuses not just on treating injuries, but on identifying and correcting the root causes before they become limitations.',
      'He holds professional certification in physiotherapy and rehabilitation, reinforcing his ability to deliver structured, evidence-based recovery and injury management solutions.',
      'His approach aligns with the PURE X philosophy — integrating physiotherapy into training from day one, rather than treating it as a reactive service. By combining clinical knowledge with real-world application, Krishna ensures that clients can train safely, progress consistently, and build long-term physical resilience.',
    ],
    responsibilities: [
      'Perform comprehensive musculoskeletal assessments during client onboarding',
      'Identify movement dysfunctions, muscle imbalances, and injury risk factors',
      'Design corrective exercise programmes integrated into training plans',
      'Deliver dedicated physiotherapy sessions focused on mobility, recovery, and rehabilitation',
      'Manage acute and chronic injuries — assessment, treatment, and return-to-training protocols',
      'Prescribe mobility, flexibility, and soft tissue management routines',
      'Monitor recovery quality and advise on sleep, stress, and regeneration strategies',
      'Collaborate closely with trainers to modify exercise selection and training load',
      'Support injury prevention through proactive monitoring and early intervention',
      'Ensure clients maintain movement quality, joint health, and long-term physical sustainability',
    ],
  },
  {
    slug: 'siva-jampana',
    name: 'Siva Jampana',
    title: 'Co-Founder & Operations Head',
    shortRole: 'Co-Founder',
    bioShort:
      'Mechanical engineer turned systems builder. Trained 10,000+ professionals, competes in HYROX Pro Doubles, and delivers the PURE X client experience end-to-end.',
    credentials: [
      'MEng Engineering Management (Distinction)',
      'Indo-German Chamber Certified Technical Trainer',
      'HYROX Pro Doubles Competitor',
      '10,000+ Professionals Trained',
      '15+ Years Business Experience',
    ],
    specialisms: [
      'Client Experience',
      'Programme Delivery',
      'HYROX Performance',
      'Business Development',
      'Systems Thinking',
      'Operational Excellence',
    ],
    yearsExperience: 15,
    clientsTrained: 10000,
    location: 'London',
    photoUrl: '/experts/siva-jampana.jpg',
    stat: { num: '10k+', label: 'Professionals Trained' },
    bioLong: [
      'Siva Jampana ensures that the PURE X client experience is seamless, structured, and delivered to the highest standard from first interaction through ongoing programme execution. As Founder and Operations Head, he plays a critical role in translating PURE X\'s performance-driven philosophy into a consistent, premium service experience.',
      'With a background in Mechanical Engineering and professional experience in the automotive industry, Siva brings strong systems thinking, process discipline, and execution excellence into the PURE X ecosystem. He has trained over 10,000+ technical and sales professionals, and is an Indo-German Chamber of Commerce certified Technical Trainer — reflecting his expertise in communication, coaching, and structured learning delivery at scale.',
      'He holds a Master\'s degree in Engineering Management with distinction. After navigating significant personal and professional challenges, he rebuilt his career from scratch in the United Kingdom, establishing himself professionally while simultaneously committing to his own physical transformation.',
      'Through disciplined training and lifestyle change, Siva achieved a 20kg weight loss, developed significant strength and physique, and progressed to competing in HYROX Pro Doubles — embodying the exact transformation journey that PURE X delivers to its clients. This unique combination of engineering precision, coaching experience, and lived transformation allows him to deeply understand the client journey — not just operationally, but personally.',
    ],
    responsibilities: [
      'Oversee the end-to-end client journey — from initial enquiry to active programme engagement',
      'Manage scheduling, session coordination, and all operational logistics',
      'Ensure consistent delivery of a premium, high-performance client experience',
      'Drive business development, partnerships, and brand growth initiatives',
      'Coordinate team workflows and cross-functional communication',
      'Lead onboarding processes, ensuring seamless integration across medical, physio, and training',
      'Manage client communication systems, engagement, and feedback loops',
      'Apply structured, systems-driven thinking to optimise service delivery',
      'Leverage experience training 10,000+ professionals to enhance client education and programme clarity',
      'Contribute real-world insights from his personal transformation and HYROX experience',
    ],
  },
  {
    slug: 'amber-jasari',
    name: 'Amber Jasari',
    title: 'Mental Health Consultant',
    shortRole: 'Mental',
    bioShort:
      'London-based, UK-trained mental health consultant. Trauma-informed, person-centred care that brings the mind-body connection into every PURE X plan.',
    credentials: [
      'CPBAB Certified',
      'Trained Mental Health First Aider',
      'Therapeutic Psychology & Counselling',
      'UK Mental Health System Experience',
      'Qualified Mental Health Support Worker',
    ],
    specialisms: [
      'Emotional Resilience',
      'Stress & Anxiety Management',
      'Trauma-Informed Care',
      'Mind-Body Integration',
      'Lifestyle Imbalance Support',
      'Young People & Additional Needs',
    ],
    yearsExperience: 4,
    location: 'London',
    photoUrl: '/experts/amber-jasari.jpg',
    stat: { num: 'London', label: 'UK Trained' },
    bioLong: [
      'Amber Jasari brings a vital dimension to the PURE X ecosystem — mental and emotional well-being. Based in London, she has completed her education in the United Kingdom, where mental health care is highly prioritised and structured around evidence-based, person-centred practices.',
      'With a background in Therapeutic Psychology and Counselling, Amber offers a compassionate and supportive space for individuals looking to improve their mental and overall well-being. Her approach is rooted in holistic health and integrative psychotherapy, focusing on the connection between the mind and body.',
      'She works closely with clients to help them build emotional resilience, navigate personal challenges, and create meaningful, lasting change in their lives. Amber is CPBAB certified and a trained Mental Health First Aider and First Aider, with hands-on experience in mental health nursing support and working as a qualified mental health support worker.',
      'She follows a trauma-informed, inclusive, and person-centred approach, ensuring that every client feels understood, respected, and supported. Her goal is to create a calm, safe, and non-judgmental environment where clients feel empowered to explore their thoughts and emotions at their own pace — building awareness, confidence, and long-term emotional resilience.',
    ],
    responsibilities: [
      'Provide mental health and emotional well-being support as part of the PURE X integrated transformation model',
      'Conduct 1-on-1 sessions focused on stress management, self-awareness, and emotional resilience',
      'Apply trauma-informed and person-centred approaches tailored to individual client needs',
      'Support clients navigating stress, anxiety, lifestyle imbalance, and emotional challenges',
      'Offer early-stage mental health intervention and guidance in more complex situations',
      'Promote the mind-body connection as a core part of overall health and performance',
      'Help clients build sustainable mental habits that support long-term lifestyle transformation',
      'Collaborate with trainers, physiotherapists, and medical professionals for holistic client experience',
      'Support young individuals and clients with additional needs in developing emotional awareness',
      'Create a safe, calm, and non-judgmental environment for open and meaningful conversations',
    ],
  },
  {
    slug: 'paula-konasionok',
    name: 'Paula Konasionok',
    title: 'Athlete Trainer',
    shortRole: 'Athlete',
    bioShort:
      'CIMSPA-endorsed UK coach bringing internationally certified performance training to PURE X. HYROX, IRONMAN, and hybrid athlete specialist.',
    credentials: [
      'CIMSPA Endorsed — UK',
      'Internationally Certified Personal Trainer',
      'Nutrition Accredited Professional',
      'Performance Coach',
    ],
    specialisms: [
      'HYROX Training',
      'IRONMAN Prep',
      'Endurance Conditioning',
      'Strength-Endurance Integration',
      'Competition Prep',
      'Hybrid Athletic Development',
    ],
    yearsExperience: 7,
    location: 'London',
    photoUrl: '/experts/paula-konasionok.jpg' as string | null,
    stat: { num: 'UK', label: 'CIMSPA Certified' },
    bioLong: [
      'Paula Konasionok is an internationally certified Personal Trainer and nutrition-accredited professional, bringing a high-performance, athlete-focused approach to training at PURE X. With her CIMSPA endorsement, she strengthens the brand\'s global credibility and elevates the standard of coaching delivery across both individual and performance-based programmes.',
      'Her expertise lies in developing athletic conditioning, strength-endurance integration, and performance optimisation for clients preparing for HYROX, IRONMAN, and general athletic transformation.',
      'Paula\'s methodology blends evidence-based conditioning science with real-world athletic application — ensuring clients build not just fitness, but race readiness.',
    ],
    responsibilities: [
      'Deliver high-quality 1-on-1 and group training sessions with a focus on athletic performance',
      'Design and implement strength, endurance, and hybrid training programmes aligned with PURE X methodology',
      'Support HYROX and endurance athletes with sport-specific training techniques and conditioning protocols',
      'Provide nutrition guidance aligned with training demands, performance goals, and recovery needs',
      'Ensure correct exercise technique, movement efficiency, and injury prevention during all sessions',
      'Collaborate with the Physiotherapist and Doctor to adapt training based on client health',
      'Assist in performance tracking, progress assessments, and programme refinement',
      'Contribute to client motivation, accountability, and overall training experience',
      'Support competition preparation including conditioning strategies, pacing, and readiness',
    ],
  },
] as const;

export const FALLBACK_PROGRAMS = [
  {
    slug: 'pure-foundation',
    name: 'Pure Foundation',
    tag: 'Start Here',
    tagline: 'Start with clarity. Build your base.',
    description:
      'Entry-level onboarding to understand your goals, lifestyle, and health — then deliver a structured plan you can actually follow. Clarity and direction before any further commitment.',
    priceInr: 1999,
    priceDisplay: '₹1,999',
    priceSuffix: '',
    durationMonths: 1,
    isFeatured: false,
    inclusions: [
      'Client profiling — goals, lifestyle, health',
      'Personalised workout plan',
      'Diet guidance',
      'Water & sleep targets',
      'Daily schedule',
      'Weight tracking',
      '1 progress call',
    ],
  },
  {
    slug: 'pure-core',
    name: 'Pure Core',
    tag: 'Most Popular',
    tagline: 'Your transformation system begins here.',
    description:
      'The full PURE X transformation system. Accountability, tracking, and consistency delivered through integrated app tracking, doctor and physio access, weekly calls, and real community.',
    priceInr: 4999,
    priceDisplay: '₹4,999',
    priceSuffix: '/month',
    durationMonths: 3,
    isFeatured: true,
    inclusions: [
      'Everything in Foundation',
      'Doctor consultation',
      'Physiotherapy assessment',
      'Full app tracking — steps, meals, water, sleep',
      'Streak system',
      'AI chat support',
      'Weekly progress calls',
      'Challenges & competitions',
    ],
  },
  {
    slug: 'pure-elite',
    name: 'Pure Elite',
    tag: 'Performance',
    tagline: 'Train like an athlete. Live like one.',
    description:
      'Premium performance and lifestyle membership. 1-on-1 coaching, HYROX and Ironman preparation, outdoor sessions, weekly expert access, and full club & community membership.',
    priceInr: 19999,
    priceDisplay: '₹19,999',
    priceSuffix: '/month',
    durationMonths: 6,
    isFeatured: false,
    inclusions: [
      'Everything in Core',
      '1-on-1 performance training',
      'HYROX / Ironman / Marathon prep',
      'Weekly outdoor training sessions',
      'PURE X club & community access',
      'Weekly expert access (Doctor / Physio / Mental Health)',
      'Advanced performance tracking',
      'Competition readiness',
    ],
  },
  {
    slug: 'elite-couple',
    name: 'Elite Couple',
    tag: 'Signature',
    tagline: 'Both partners. HYROX-focused. Doubles race prep included.',
    description:
      'Two athletes, one plan. Built around shared goals and HYROX Doubles race preparation. The most popular programme for high-performing couples transforming together.',
    priceInr: 29999,
    priceDisplay: '₹29,999',
    priceSuffix: '/month',
    durationMonths: 4,
    isFeatured: false,
    inclusions: [
      'Joint training sessions (3-4 per week)',
      'Individual physio and doctor consultations',
      'Combined nutrition plan',
      'HYROX Doubles race preparation',
      '24hr coach access for both partners',
      'Monthly couples performance review',
      'Shared progress tracking',
      'Access to PURE X community events',
    ],
  },
] as const;

export const FALLBACK_TRANSFORMATIONS = [
  {
    slug: 'arjun-hyrox-16wk',
    clientName: 'Arjun M.',
    goal: 'HYROX Preparation',
    durationWeeks: 16,
    headline: 'Engineer to HYROX finisher in 16 weeks.',
    stats: [
      { label: 'Body fat', value: '−8kg' },
      { label: 'Strength', value: '+12kg' },
      { label: 'HYROX time', value: '52min' },
    ],
    expert: 'siva-reddy',
    program: 'pure-elite',
  },
  {
    slug: 'priya-rohan-couple-24wk',
    clientName: 'Priya & Rohan',
    goal: 'HYROX Doubles',
    durationWeeks: 24,
    headline: 'Two busy professionals. One HYROX Doubles podium.',
    stats: [
      { label: 'Combined loss', value: '−14kg' },
      { label: 'HYROX Doubles', value: '2×' },
      { label: 'Max HR', value: '180bpm' },
    ],
    expert: 'paula-konasionok',
    program: 'pure-elite',
  },
  {
    slug: 'vikram-ironman-36wk',
    clientName: 'Vikram S.',
    goal: 'IRONMAN 70.3',
    durationWeeks: 36,
    headline: 'First triathlon to sub-6-hour IRONMAN finish.',
    stats: [
      { label: 'Finish time', value: '5:48' },
      { label: 'Body fat', value: '−11kg' },
      { label: 'Resting HR', value: '58' },
    ],
    expert: 'paula-konasionok',
    program: 'pure-elite',
  },
  {
    slug: 'meera-online-12wk',
    clientName: 'Meera K.',
    goal: 'Online Transformation',
    durationWeeks: 12,
    headline: 'Remote coaching, measurable results.',
    stats: [
      { label: 'Body fat', value: '−6kg' },
      { label: 'VO2 max', value: '+30%' },
      { label: 'Injuries', value: '0' },
    ],
    expert: 'siva-reddy',
    program: 'pure-core',
  },
  {
    slug: 'karthik-fat-loss-20wk',
    clientName: 'Karthik R.',
    goal: 'Fat Loss + Strength',
    durationWeeks: 20,
    headline: 'Eighteen kilos gone. Deadlift doubled.',
    stats: [
      { label: 'Weight lost', value: '−18kg' },
      { label: 'Body fat %', value: '22%' },
      { label: 'Deadlift', value: '100kg' },
    ],
    expert: 'siva-reddy',
    program: 'pure-elite',
  },
  {
    slug: 'ananya-injury-recovery-14wk',
    clientName: 'Ananya D.',
    goal: 'Injury Recovery',
    durationWeeks: 14,
    headline: 'From chronic back pain to fully pain-free training.',
    stats: [
      { label: 'Pain score', value: '0/10' },
      { label: 'Muscle gain', value: '+8kg' },
      { label: 'Movement', value: 'A+' },
    ],
    expert: 'krishna',
    program: 'pure-elite',
  },
] as const;

export const FALLBACK_FAQS = [
  {
    category: 'Booking',
    question: 'How do I start with PURE X?',
    answer: 'Book a free 30-minute discovery call. We\'ll understand your goals, health history, and recommend the right programme. Your onboarding starts within 7-10 days.',
  },
  {
    category: 'Booking',
    question: 'Can I train online or does it have to be in-person?',
    answer: 'Both. Our Pure Core plan gives you app tracking, weekly calls, and remote doctor and physio access from anywhere. In-person 1-on-1 training is available on Pure Elite and Elite Couple plans in Hyderabad.',
  },
  {
    category: 'Pricing',
    question: 'Why is PURE X more expensive than a regular personal trainer?',
    answer: 'You\'re not hiring one person. You get a trainer, doctor, physiotherapist, and athletic coach working from one coordinated plan. The price reflects an integrated team, not a solo coach.',
  },
  {
    category: 'Training',
    question: 'Do I need prior gym experience?',
    answer: 'No. We start every client with a full medical and physiotherapy screen, then design the programme around their current fitness level. Beginners and experienced athletes both start with a personalised baseline.',
  },
  {
    category: 'Medical',
    question: 'What if I have an injury or medical condition?',
    answer: 'Our consultant doctor conducts a full health screen before training begins. Krishna (physiotherapist) designs corrective work around any limitations. Many of our most successful clients came to us with existing injuries.',
  },
  {
    category: 'HYROX',
    question: 'Do you coach HYROX specifically?',
    answer: 'Yes. Siva Reddy is HYROX-certified and Siva Jampana has competed in HYROX Pro Doubles. We have structured 16-week HYROX preparation cycles for individuals and couples.',
  },
] as const;

export type Expert = typeof FALLBACK_EXPERTS[number];
export type Program = typeof FALLBACK_PROGRAMS[number];
export type Transformation = typeof FALLBACK_TRANSFORMATIONS[number];
export type FaqItem = typeof FALLBACK_FAQS[number];
