export const BRAND = {
  name: 'PURE X',
  tagline: 'Train for Life. Not Just Aesthetics.',
  whatsapp: '+919999999999', // replace with real number
  email: 'contact.teampurex@gmail.com', // public-facing email
  internalEmail: 'info.teampurex@gmail.com', // internal/admin notifications
  locations: ['India', 'UK'],
} as const;

export const whatsappLink = (message = 'Hi PURE X, I would like to know more.') =>
  `https://wa.me/${BRAND.whatsapp.replace(/\D/g, '')}?text=${encodeURIComponent(message)}`;

// Fallback data — used before Supabase is wired. Admin panel will replace with DB reads.
export const FALLBACK_EXPERTS = [
  {
    slug: 'siva-reddy',
    name: 'Siva Reddy',
    title: 'Co-Founder & Personal Training Head',
    shortRole: 'PT Head',
    bioShort:
      'ICN medalist and architect of every PURE X training programme. Engineer-turned-coach with 300+ clients coached across strength, HYROX, rehab, and athletic performance.',
    credentials: [
      'ICN Gold 2024 — Best Transformation',
      'ICN Bronze 2024 — Men\'s Fitness Model',
      'Powerlifting Trainer (INPTA)',
      'Injury Rehabilitation Trainer',
      'Diploma in Personal Training',
      'Diploma in Nutrition',
    ],
    specialisms: [
      'HYROX Training',
      'Strength & Powerlifting',
      'Fat Loss',
      'Injury Rehab',
      'Calisthenics',
      'Post-Pregnancy Recovery',
    ],
    yearsExperience: 5,
    clientsTrained: 300,
    location: 'India',
    photoUrl: '/experts/siva-reddy.jpg',
    stat: { num: '300+', label: 'Clients Coached' },
    bioLong: [
      'Siva Reddy is the architectural force behind every PURE X training programme. As Personal Training Head, he leads the design and evolution of structured, performance-driven systems—ensuring every client experiences scientifically grounded and result-oriented training.',
      'His journey into fitness began through personal transformation. With a background in Electronics and Communications Engineering, Siva started in the corporate world, where stress and lifestyle challenges affected his health. This became the turning point that led him to rebuild his life through disciplined training and structured habits.',
      'Through consistency and focused programming, Siva achieved a 40kg weight loss, transforming both his physique and mindset. His journey led him to the competitive stage, earning a Gold Medal in Best Transformation and Bronze in Men\'s Fitness Model at ICN 2024.',
      'Driven by purpose, he transitioned fully into the fitness industry and now holds multiple professional certifications aligned with INPTA and ISO standards. Having coached 300+ clients across fat loss, muscle building, hormonal balance, post-pregnancy recovery, injury rehabilitation, and calisthenics, Siva blends technical precision with real-world adaptability.',
      'More than a coach, he is a system builder—creating structured pathways that help individuals become stronger, healthier, and more capable for life.',
    ],
    responsibilities: [],
  },
  {
    slug: 'chandralekha',
    name: 'Chandralekha',
    title: 'Consultant Doctor',
    shortRole: 'Doctor',
    bioShort:
      'Consultant doctor bringing real clinical rigour to every PURE X programme. Turns fitness into medically supervised health transformation.',
    credentials: [
      'Pre-programme Medical Screening',
      'Cardiovascular & Metabolic Health',
      'Risk Stratification',
      '7+ Years Clinical Experience',
    ],
    specialisms: [
      'Medical Screening',
      'Cardiovascular Health',
      'Metabolic Assessment',
      'Chronic Condition Management',
      'Sustainable Health Habits',
    ],
    yearsExperience: 7,
    location: 'India',
    photoUrl: '/experts/chandralekha.jpg',
    stat: { num: '100%', label: 'Medical Clearance' },
    bioLong: [
      'Chandralekha plays a key role in strengthening the PURE X approach through education and awareness, bringing a strong medical perspective to health, recovery, and safe training practices. Her contribution supports the transition from traditional fitness to a more informed and sustainable approach to overall well-being.',
      'With extensive clinical experience, she brings a deep understanding of patient care, health monitoring, and lifestyle-related conditions. Her insights help individuals approach fitness with greater clarity, safety, and long-term focus.',
      'Beyond her professional work, Chandralekha is also a mother of two, balancing career and family life. This gives her a practical understanding of the challenges many individuals face — including time constraints, stress, and the need for realistic, sustainable health solutions.',
      'Her approach aligns closely with the PURE X philosophy — focusing not just on fitness, but on building safe, consistent, and long-term lifestyle transformation.',
    ],
    responsibilities: [],
  },
  {
    slug: 'krishna',
    name: 'Krishna',
    title: 'Physiotherapist',
    shortRole: 'Physio',
    bioShort:
      'Prevention-first physiotherapy embedded into training from day one. 1,000+ clients treated, backed by 5+ years of hands-on clinical experience.',
    credentials: [
      'Certified Physiotherapist',
      'Rehabilitation Specialist',
      'Movement Screening Expert',
      '5+ Years Clinical Experience',
    ],
    specialisms: [
      'Injury Prevention',
      'Movement Screening',
      'Rehabilitation',
      'Mobility & Soft Tissue',
      'Return-to-Training Protocols',
      'Corrective Exercise',
    ],
    yearsExperience: 5,
    clientsTrained: 1000,
    location: 'India',
    photoUrl: '/experts/krishna.jpg' as string | null,
    stat: { num: '1000+', label: 'Clients Treated' },
    bioLong: [
      'Krishna plays a critical role in ensuring that every PURE X client moves efficiently, recovers effectively, and trains consistently without setbacks. As the Physiotherapist, he brings a proactive, prevention-first approach that is deeply integrated into the PURE X training system.',
      'With over 5 years of professional experience and having supported 1,000+ clients, Krishna brings extensive hands-on expertise in injury prevention, rehabilitation, and movement optimisation. His work focuses not just on treating injuries, but on identifying and correcting the root causes before they become limitations.',
      'He holds professional certification in physiotherapy and rehabilitation, reinforcing his ability to deliver structured, evidence-based recovery and injury management solutions.',
      'His approach aligns with the PURE X philosophy — integrating physiotherapy into training from day one, rather than treating it as a reactive service. By combining clinical knowledge with real-world application, Krishna ensures that clients can train safely, progress consistently, and build long-term physical resilience.',
    ],
    responsibilities: [],
  },
  {
    slug: 'siva-jampana',
    name: 'Siva Jampana',
    title: 'Co-Founder & Operations Head',
    shortRole: 'Co-Founder',
    bioShort:
      'Co-founder driving the PURE X vision. Endurance athlete, lifestyle coach, and HYROX Pro Doubles competitor delivering the client experience end-to-end.',
    credentials: [
      'MEng Engineering Management (Distinction)',
      'Indo-German Chamber Certified Technical Trainer',
      'HYROX Pro Doubles Competitor',
      'Endurance & Resilience Training',
      'Lifestyle Coaching',
    ],
    specialisms: [
      'Client Experience',
      'Programme Delivery',
      'HYROX Performance',
      'Endurance Training',
      'Lifestyle Coaching',
      'Operational Excellence',
    ],
    yearsExperience: 15,
    clientsTrained: 10000,
    location: 'UK',
    photoUrl: '/experts/siva-jampana.jpg',
    stat: { num: 'HYROX', label: 'Pro Doubles' },
    bioLong: [
      'Siva Jampana drives the vision behind PURE X, ensuring every client journey is structured, performance-focused, and aligned with long-term lifestyle transformation. His approach combines systems thinking with real-world experience to deliver a consistent and premium training ecosystem.',
      'With a background in Mechanical Engineering and experience in the automotive industry, Siva brings strong execution, discipline, and scalable thinking into PURE X. He has trained over 10,000+ professionals and is an Indo-German Chamber of Commerce certified Technical Trainer, reflecting his ability to build structured learning and coaching systems.',
      'His personal journey is deeply rooted in endurance and resilience. Having completed multiple long-distance cycling challenges—including two 1300km rides and a 600km barefoot ride—Siva brings firsthand experience in endurance training and mental discipline. This forms a strong foundation for his focus on hybrid performance and Ironman-style training.',
      'Alongside his practical experience, he is currently advancing his expertise through Personal Training and Nutrition certifications, aligning with the PURE X philosophy of continuous learning and development.',
      'Having transformed his own lifestyle through a 20kg weight loss and competitive HYROX participation, Siva embodies the PURE X mission — building individuals who are stronger, more capable, and prepared for real-life performance.',
    ],
    responsibilities: [],
  },
  {
    slug: 'amber-jasari',
    name: 'Amber Jasari',
    title: 'Mental Health Consultant',
    shortRole: 'Mental',
    bioShort:
      'UK-based, UK-trained mental health consultant. Trauma-informed, person-centred care that brings the mind-body connection into every PURE X plan.',
    credentials: [
      'CPBAB Certified',
      'Trained Mental Health First Aider',
      'Therapeutic Psychology & Counselling',
      'UK Mental Health System Experience',
      'Qualified Mental Health Support Worker',
    ],
    specialisms: [
      'Emotional Resilience',
      'Stress & Anxiety Management',
      'Trauma-Informed Care',
      'Mind-Body Integration',
      'Lifestyle Imbalance Support',
      'Young People & Additional Needs',
    ],
    yearsExperience: 4,
    location: 'UK',
    photoUrl: '/experts/amber-jasari.jpg',
    stat: { num: 'UK', label: 'UK Trained' },
    bioLong: [
      'Amber Jasari brings a vital dimension to the PURE X ecosystem — mental and emotional well-being. Based in London, she has completed her education in the United Kingdom, where mental health care is highly prioritised and structured around evidence-based, person-centred practices.',
      'With a background in Therapeutic Psychology and Counselling, Amber offers a compassionate and supportive space for individuals looking to improve their mental and overall well-being. Her approach is rooted in holistic health and integrative psychotherapy, focusing on the connection between the mind and body.',
      'She works closely with clients to help them build emotional resilience, navigate personal challenges, and create meaningful, lasting change in their lives. Amber is CPBAB certified and a trained Mental Health First Aider and First Aider, with hands-on experience in mental health nursing support and working as a qualified mental health support worker.',
      'She follows a trauma-informed, inclusive, and person-centred approach, ensuring that every client feels understood, respected, and supported. Her goal is to create a calm, safe, and non-judgmental environment where clients feel empowered to explore their thoughts and emotions at their own pace — building awareness, confidence, and long-term emotional resilience.',
    ],
    responsibilities: [],
  },
  {
    slug: 'paula-konasionok',
    name: 'Paula Konasionok',
    title: 'Athlete Trainer',
    shortRole: 'Athlete',
    bioShort:
      'CIMSPA-endorsed UK coach bringing internationally certified performance training to PURE X. HYROX, IRONMAN, and hybrid athlete specialist.',
    credentials: [
      'CIMSPA Endorsed — UK',
      'Internationally Certified Personal Trainer',
      'Nutrition Accredited Professional',
      'Performance Coach',
    ],
    specialisms: [
      'HYROX Training',
      'IRONMAN Prep',
      'Endurance Conditioning',
      'Strength-Endurance Integration',
      'Competition Prep',
      'Hybrid Athletic Development',
    ],
    yearsExperience: 7,
    location: 'UK',
    photoUrl: '/experts/paula-konasionok.jpg' as string | null,
    stat: { num: 'UK', label: 'CIMSPA Certified' },
    bioLong: [
      'Paula Konasionok is an internationally certified Personal Trainer and nutrition-accredited professional, bringing a high-performance, athlete-focused approach to training at PURE X. With her CIMSPA endorsement, she strengthens the brand\'s global credibility and elevates the standard of coaching delivery across both individual and performance-based programmes.',
      'Her expertise lies in developing athletic conditioning, strength-endurance integration, and performance optimisation for clients preparing for HYROX, IRONMAN, and general athletic transformation.',
      'Paula\'s methodology blends evidence-based conditioning science with real-world athletic application — ensuring clients build not just fitness, but race readiness.',
    ],
    responsibilities: [],
  },
] as const;

export const FALLBACK_PROGRAMS = [
  {
    slug: 'pure-foundation',
    name: 'Pure Foundation',
    tag: 'Start Here',
    tagline: 'Start with clarity. Build your base.',
    description:
      'Entry-level onboarding to understand your goals, lifestyle, and health — then deliver a structured plan you can actually follow. Clarity and direction before any further commitment.',
    priceInr: 1999,
    priceDisplay: '₹1,999',
    priceSuffix: '',
    durationMonths: 1,
    isFeatured: false,
    isPremium: false,
    inclusions: [
      'Client profiling — goals, lifestyle, health',
      'Personalised workout plan',
      'Diet guidance',
      'Water & sleep targets',
      'Daily schedule',
      'Weight tracking',
      '1 progress call',
    ],
  },
  {
    slug: 'pure-core',
    name: 'Pure Core',
    tag: 'Most Popular',
    tagline: 'Your transformation system begins here.',
    description:
      'The full PURE X transformation system. Accountability, tracking, and consistency delivered through integrated app tracking, doctor and physio access, weekly calls, and real community.',
    priceInr: 4999,
    priceDisplay: '₹4,999',
    priceSuffix: '/month',
    durationMonths: 3,
    isFeatured: true,
    isPremium: false,
    inclusions: [
      'Everything in Foundation',
      'Doctor consultation',
      'Physiotherapy assessment',
      'Full app tracking — steps, meals, water, sleep',
      'Streak system',
      'AI chat support',
      'Weekly progress calls',
      'Challenges & competitions',
    ],
  },
  {
    slug: 'pure-elite',
    name: 'Pure Elite',
    tag: 'Performance',
    tagline: 'Train like an athlete. Live like one.',
    description:
      'Premium performance and lifestyle membership. 1-on-1 coaching, HYROX and Ironman preparation, outdoor sessions, weekly expert access, and full club & community membership.',
    priceInr: 19999,
    priceDisplay: '₹19,999',
    priceSuffix: '/month',
    durationMonths: 6,
    isFeatured: false,
    isPremium: false,
    inclusions: [
      'Everything in Core',
      '1-on-1 performance training',
      'HYROX / Ironman / Marathon prep',
      'Weekly outdoor training sessions',
      'PURE X club & community access',
      'Weekly expert access (Doctor / Physio / Mental Health)',
      'Advanced performance tracking',
      'Competition readiness',
    ],
  },
  {
    slug: 'elite-couple',
    name: 'Elite Couple',
    tag: 'Signature',
    tagline: 'Both partners. HYROX-focused. Doubles race prep included.',
    description:
      'Two athletes, one plan. Built around shared goals and HYROX Doubles race preparation. The most popular programme for high-performing couples transforming together.',
    priceInr: 29999,
    priceDisplay: '₹29,999',
    priceSuffix: '/month',
    durationMonths: 4,
    isFeatured: false,
    isPremium: false,
    inclusions: [
      'Joint training sessions (3-4 per week)',
      'Individual physio and doctor consultations',
      'Combined nutrition plan',
      'HYROX Doubles race preparation',
      '24hr coach access for both partners',
      'Monthly couples performance review',
      'Shared progress tracking',
      'Access to PURE X community events',
    ],
  },
  {
    slug: 'enduro',
    name: 'Enduro',
    tag: 'Race Prep',
    tagline: 'For HYROX, IRONMAN, and hybrid athletes built for the long event.',
    description:
      'A specialist programme for athletes preparing for HYROX, IRONMAN, and other endurance events. Combines structured periodisation, race-specific conditioning, and the lived experience of HYROX Pro Doubles competitors. The most demanding programme PURE X offers — and the most rewarding.',
    priceInr: 24999,
    priceDisplay: '₹24,999',
    priceSuffix: '/month',
    durationMonths: 4,
    isFeatured: false,
    isPremium: true,
    inclusions: [
      'Structured race-day preparation (HYROX or IRONMAN)',
      'Periodised training cycles with taper protocols',
      'Strength + endurance hybrid programming',
      'Movement screening + injury prevention',
      'Direct access to Siva Jampana (HYROX Pro Doubles)',
      'Race-day strategy session and equipment check',
      'Mental performance coaching with Amber',
      'Recovery and nutrition optimised for race demands',
      'Weekly performance reviews with the full team',
      '1-on-1 coaching across all 6 specialists',
    ],
  },
] as const;

export const FALLBACK_TRANSFORMATIONS = [
  {
    slug: 'arjun-hyrox-16wk',
    clientName: 'Arjun M.',
    goal: 'HYROX Preparation',
    durationWeeks: 16,
    headline: 'Engineer to HYROX finisher in 16 weeks.',
    stats: [
      { label: 'Body fat', value: '−8kg' },
      { label: 'Strength', value: '+12kg' },
      { label: 'HYROX time', value: '52min' },
    ],
    expert: 'siva-reddy',
    program: 'pure-elite',
  },
  {
    slug: 'priya-rohan-couple-24wk',
    clientName: 'Priya & Rohan',
    goal: 'HYROX Doubles',
    durationWeeks: 24,
    headline: 'Two busy professionals. One HYROX Doubles podium.',
    stats: [
      { label: 'Combined loss', value: '−14kg' },
      { label: 'HYROX Doubles', value: '2×' },
      { label: 'Max HR', value: '180bpm' },
    ],
    expert: 'paula-konasionok',
    program: 'pure-elite',
  },
  {
    slug: 'vikram-ironman-36wk',
    clientName: 'Vikram S.',
    goal: 'IRONMAN 70.3',
    durationWeeks: 36,
    headline: 'First triathlon to sub-6-hour IRONMAN finish.',
    stats: [
      { label: 'Finish time', value: '5:48' },
      { label: 'Body fat', value: '−11kg' },
      { label: 'Resting HR', value: '58' },
    ],
    expert: 'paula-konasionok',
    program: 'pure-elite',
  },
  {
    slug: 'meera-online-12wk',
    clientName: 'Meera K.',
    goal: 'Online Transformation',
    durationWeeks: 12,
    headline: 'Remote coaching, measurable results.',
    stats: [
      { label: 'Body fat', value: '−6kg' },
      { label: 'VO2 max', value: '+30%' },
      { label: 'Injuries', value: '0' },
    ],
    expert: 'siva-reddy',
    program: 'pure-core',
  },
  {
    slug: 'karthik-fat-loss-20wk',
    clientName: 'Karthik R.',
    goal: 'Fat Loss + Strength',
    durationWeeks: 20,
    headline: 'Eighteen kilos gone. Deadlift doubled.',
    stats: [
      { label: 'Weight lost', value: '−18kg' },
      { label: 'Body fat %', value: '22%' },
      { label: 'Deadlift', value: '100kg' },
    ],
    expert: 'siva-reddy',
    program: 'pure-elite',
  },
  {
    slug: 'ananya-injury-recovery-14wk',
    clientName: 'Ananya D.',
    goal: 'Injury Recovery',
    durationWeeks: 14,
    headline: 'From chronic back pain to fully pain-free training.',
    stats: [
      { label: 'Pain score', value: '0/10' },
      { label: 'Muscle gain', value: '+8kg' },
      { label: 'Movement', value: 'A+' },
    ],
    expert: 'krishna',
    program: 'pure-elite',
  },
] as const;

export const FALLBACK_FAQS = [
  {
    category: 'Booking',
    question: 'How do I start with PURE X?',
    answer: 'Book a free 30-minute discovery call. We\'ll understand your goals, health history, and recommend the right programme. Your onboarding starts within 7-10 days.',
  },
  {
    category: 'Booking',
    question: 'Can I train online or does it have to be in-person?',
    answer: 'Both. Our Pure Core plan gives you app tracking, weekly calls, and remote doctor and physio access from anywhere. In-person 1-on-1 training is available on Pure Elite and Elite Couple plans in Hyderabad.',
  },
  {
    category: 'Pricing',
    question: 'Why is PURE X more expensive than a regular personal trainer?',
    answer: 'You\'re not hiring one person. You get a trainer, doctor, physiotherapist, and athletic coach working from one coordinated plan. The price reflects an integrated team, not a solo coach.',
  },
  {
    category: 'Training',
    question: 'Do I need prior gym experience?',
    answer: 'No. We start every client with a full medical and physiotherapy screen, then design the programme around their current fitness level. Beginners and experienced athletes both start with a personalised baseline.',
  },
  {
    category: 'Medical',
    question: 'What if I have an injury or medical condition?',
    answer: 'Our consultant doctor conducts a full health screen before training begins. Krishna (physiotherapist) designs corrective work around any limitations. Many of our most successful clients came to us with existing injuries.',
  },
  {
    category: 'HYROX',
    question: 'Do you coach HYROX specifically?',
    answer: 'Yes. Siva Reddy is HYROX-certified and Siva Jampana has competed in HYROX Pro Doubles. We have structured 16-week HYROX preparation cycles for individuals and couples.',
  },
] as const;

export type Expert = typeof FALLBACK_EXPERTS[number];
export type Program = typeof FALLBACK_PROGRAMS[number];
export type Transformation = typeof FALLBACK_TRANSFORMATIONS[number];
export type FaqItem = typeof FALLBACK_FAQS[number];
