'use server';

import { redirect } from 'next/navigation';
import { headers } from 'next/headers';
import { createClient } from '@/lib/supabase/server';
import { bookingSubmitSchema, type BookingSubmitInput } from '@/lib/validations/booking';
import { getServiceById } from '@/lib/services';
import { FALLBACK_EXPERTS } from '@/lib/constants';

export type BookingActionState = {
  ok: boolean;
  error?: string;
  fieldErrors?: Record<string, string>;
  bookingRef?: string;
};

/**
 * Submit a booking from the public marketing site.
 *
 * Flow:
 *   1. Validate input with Zod
 *   2. Look up service & expert for denormalized display
 *   3. Insert into Supabase `bookings` table (RLS: anyone can create)
 *   4. Also store pre-consult form responses in `form_submissions` table
 *   5. Redirect to /thank-you with the reference ID
 *
 * Fallback: if Supabase insert fails (e.g. no credentials, network issue),
 * log the booking details to the server console so the lead isn't lost.
 * The user is still redirected to thank-you.
 */
export async function submitBooking(
  _prevState: BookingActionState,
  formData: FormData
): Promise<BookingActionState> {
  // ─── Parse and validate input ──────────────────────────────────
  const rawFormResponse = formData.get('formResponse') as string | null;
  let formResponse: Record<string, string | string[]> = {};
  try {
    if (rawFormResponse) formResponse = JSON.parse(rawFormResponse);
  } catch {
    return { ok: false, error: 'Invalid form data. Please try again.' };
  }

  const input: Partial<BookingSubmitInput> = {
    fullName: (formData.get('fullName') as string) ?? '',
    email: (formData.get('email') as string) ?? '',
    phone: (formData.get('phone') as string) ?? '',
    expertSlug: (formData.get('expertSlug') as string) ?? '',
    serviceId: (formData.get('serviceId') as string) ?? '',
    preferredDate: (formData.get('preferredDate') as string) ?? '',
    preferredTimeSlot:
      (formData.get('preferredTimeSlot') as
        | 'morning'
        | 'afternoon'
        | 'evening'
        | null) ?? undefined,
    alternateDate: (formData.get('alternateDate') as string) || undefined,
    format:
      (formData.get('format') as 'online' | 'in_person' | 'hybrid' | null) ??
      'online',
    formResponse,
    consent:
      formData.get('consent') === 'on' ? (true as const) : (undefined as never),
    source: 'booking_flow',
    utmSource: (formData.get('utmSource') as string) || undefined,
    utmMedium: (formData.get('utmMedium') as string) || undefined,
    utmCampaign: (formData.get('utmCampaign') as string) || undefined,
  };

  const parsed = bookingSubmitSchema.safeParse(input);
  if (!parsed.success) {
    const fieldErrors: Record<string, string> = {};
    parsed.error.issues.forEach((issue) => {
      const key = issue.path.join('.');
      if (!fieldErrors[key]) fieldErrors[key] = issue.message;
    });
    return {
      ok: false,
      error: 'Please correct the highlighted fields.',
      fieldErrors,
    };
  }

  const data = parsed.data;
  const service = getServiceById(data.serviceId);
  if (!service) {
    return { ok: false, error: 'Selected service is no longer available.' };
  }
  const expert = FALLBACK_EXPERTS.find((e) => e.slug === data.expertSlug);

  // ─── Collect meta for logging ──────────────────────────────────
  const headersList = await headers();
  const userAgent = headersList.get('user-agent') ?? 'unknown';
  const ip = headersList.get('x-forwarded-for') ?? 'unknown';

  // ─── Attempt Supabase insert ───────────────────────────────────
  let bookingRef: string | undefined;
  let insertError: string | null = null;

  try {
    const supabase = await createClient();

    // Insert the booking. `reference_id` is auto-generated by a DB default.
    const { data: inserted, error } = await supabase
      .from('bookings')
      .insert({
        client_name: data.fullName,
        client_email: data.email,
        client_phone: data.phone,

        expert_slug: data.expertSlug,
        // expert_id + service_id left null — they're set once admins
        // wire up real Supabase experts/services tables. The slug +
        // service_name denormalized fields keep the lead readable
        // without those FKs.
        service_name: service.name,

        preferred_date: data.preferredDate || null,
        preferred_time_slot: data.preferredTimeSlot,

        status: 'new',
        source: 'website',
        notes: buildLeadNotes({
          format: data.format,
          alternateDate: data.alternateDate,
          expertName: expert?.name,
          formResponse: data.formResponse,
          utm: {
            source: data.utmSource,
            medium: data.utmMedium,
            campaign: data.utmCampaign,
          },
          userAgent,
          ip,
        }),
      })
      .select('reference_id')
      .single();

    if (error) {
      insertError = error.message;
      // eslint-disable-next-line no-console
      console.error('[PURE X] Supabase booking insert failed:', error);
    } else if (inserted) {
      bookingRef = inserted.reference_id;

      // Also try to persist the pre-consult form response, best-effort
      try {
        const { data: booking } = await supabase
          .from('bookings')
          .select('id')
          .eq('reference_id', bookingRef)
          .single();

        if (booking?.id && Object.keys(data.formResponse).length > 0) {
          await supabase.from('form_submissions').insert({
            booking_id: booking.id,
            expert_slug: data.expertSlug,
            form_template_id: service.formTemplateId ?? 'unknown',
            responses: data.formResponse,
          });
        }
      } catch (err) {
        // Non-fatal — booking is still captured
        // eslint-disable-next-line no-console
        console.warn('[PURE X] form_submissions insert skipped:', err);
      }
    }
  } catch (err) {
    insertError = err instanceof Error ? err.message : 'Unknown error';
    // eslint-disable-next-line no-console
    console.error('[PURE X] Supabase client creation failed:', err);
  }

  // ─── Fallback: log the lead so it's not lost ───────────────────
  if (!bookingRef) {
    bookingRef = `PX-LOCAL-${Date.now().toString(36).toUpperCase()}`;
    // eslint-disable-next-line no-console
    console.log('[PURE X] ⚠️ DATABASE UNAVAILABLE — LEAD LOGGED LOCALLY:', {
      bookingRef,
      reason: insertError ?? 'unknown',
      client: {
        name: data.fullName,
        email: data.email,
        phone: data.phone,
      },
      expert: expert?.name ?? data.expertSlug,
      service: service.name,
      schedule: `${data.preferredDate} (${data.preferredTimeSlot}) · ${data.format}`,
      alternateDate: data.alternateDate,
      formResponse: data.formResponse,
      meta: {
        userAgent,
        ip,
        utm: {
          source: data.utmSource,
          medium: data.utmMedium,
          campaign: data.utmCampaign,
        },
      },
      submittedAt: new Date().toISOString(),
    });
  }

  // ─── Redirect to thank-you with the reference ──────────────────
  redirect(`/thank-you?ref=${bookingRef}`);
}

/**
 * Build a readable note blob that captures everything Supabase bookings
 * table doesn't have dedicated columns for (format, alternate date,
 * form responses, UTM, etc.). Admins can read this in /admin/leads.
 */
function buildLeadNotes(input: {
  format: 'online' | 'in_person' | 'hybrid';
  alternateDate?: string;
  expertName?: string;
  formResponse: Record<string, string | string[]>;
  utm: { source?: string; medium?: string; campaign?: string };
  userAgent: string;
  ip: string;
}): string {
  const lines: string[] = [];

  lines.push(`Format: ${input.format.replace('_', ' ')}`);
  if (input.expertName) lines.push(`Requested expert: ${input.expertName}`);
  if (input.alternateDate) lines.push(`Alt date: ${input.alternateDate}`);

  if (Object.keys(input.formResponse).length > 0) {
    lines.push('');
    lines.push('── Pre-consult form ──');
    for (const [key, value] of Object.entries(input.formResponse)) {
      const val = Array.isArray(value) ? value.join(', ') : value;
      const label = key.replace(/_/g, ' ');
      lines.push(`${label}: ${val}`);
    }
  }

  if (input.utm.source || input.utm.medium || input.utm.campaign) {
    lines.push('');
    lines.push('── Attribution ──');
    if (input.utm.source) lines.push(`utm_source: ${input.utm.source}`);
    if (input.utm.medium) lines.push(`utm_medium: ${input.utm.medium}`);
    if (input.utm.campaign) lines.push(`utm_campaign: ${input.utm.campaign}`);
  }

  lines.push('');
  lines.push(`Submitted: ${new Date().toISOString()}`);
  lines.push(`IP: ${input.ip}`);

  return lines.join('\n');
}
